### PR TITLE
Proper fix for GetContainerItemInfo

### PR DESCRIPTION
**Pull request by Caedis**
GetContainerItemInfo returns a ContainerItemInfo object

### CODE REVIEW

**Comment by TravisSpomer** [comment]
Thanks for this! I appreciate it. I was going to look into this more tonight and you've saved me some time. 🙂

**Comment by Caedis** [comment]
You're welcome. I have been making the same changes to several addons that have not updated yet.

**Comment by Merathilis** [comment]
Sorry to hijack this request but with your latest version we get now:

```lua
1x Interface/AddOns/Pawn/Pawn.lua:423: attempt to index local 'ItemInfo' (a nil value)
[string "@Interface/AddOns/Pawn/Pawn.lua"]:423: in function `PawnIsContainerItemAnUpgrade'
```

**Comment by TravisSpomer** [comment]
Grr. But thanks for the tip! I'll take care of that for 2.7.11.

**Pull request merged**
